name: Daily Job Alert Email

on:
  schedule:
    - cron: '30 6 * * *'  # Runs daily at 12:00 PM IST
  workflow_dispatch:

jobs:
  send-job-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Send Job Alert Email
        env:
          EMAIL: ${{ secrets.EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: |
          echo "EMAIL='${EMAIL}'" > .env
          echo "APP_PASSWORD='${APP_PASSWORD}'" >> .env
          python3 job_alert.py
